[build]
  publish = "public" # This is the default output folder for 11ty
  command = "npx eleventy" # This is the command Netlify will run to build your site

[context.production.environment]
  NODE_ENV = "production"
